image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

static:
  stage: test
  before_script:
    - pip install semgrep
  script: semgrep --error --config=p/r2c-ci .
  only:
    changes:
      - "**/*.py"
  except:
    - tags

lint:
  stage: test
  before_script:
    - pip install pylint==2.4.4 pylint-quotes git+https://gitlab.com/nwmitchell/pylint-print -r requirements.txt
  script:
    - pylint *.py
  except:
    - tags

unit:
  stage: test
  before_script:
    - pip install coverage pytest -r requirements.txt
  script:
    - coverage run --omit='tests.py' --source='./' `which pytest` *.py
  after_script:
    - coverage report
    - coverage html
  except:
    - tags
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 hour

pages:
  stage: deploy
  dependencies:
    - unit
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
  only:
    - master
  except:
    - tags
