image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

lint:
  stage: test
  before_script:
    - pip install pylint pylint-quotes -r requirements.txt
  script:
    - pylint --ignore=tests.py *.py

unit:
  stage: test
  before_script:
    - pip install coverage pytest -r requirements.txt
  script:
    - coverage run --omit='tests.py' --source='./' `which pytest` *.py
  after_script:
    - coverage report
    - coverage html
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 hour

pages:
  stage: deploy
  dependencies:
    - unit
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
  only:
    - master
