image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

lint:
  stage: test
  before_script:
    - pip install pylint pylint-quotes -r requirements.txt
  script:
    - pylint --ignore=tests.py *.py

unit:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - ./run_tests.sh
