image: python:3.8

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

static:
  image: returntocorp/semgrep-agent:v1
  script: semgrep-agent
  variables:
    SEMGREP_RULES: >-
      p/r2c-ci
  only:
    changes:
      - "**/*.py"
  except:
    - tags

lint:
  stage: test
  before_script:
    - pip install pylint==2.4.4 pylint-quotes pylint-print==1.0.0 .
  script:
    - pylint *.py
  except:
    - tags

unit:
  stage: test
  before_script:
    - pip install coverage pytest .
  script: |
    coverage run --omit='tests/*,**/__init__.py,version.py' --source='./' `which pytest` tests/tests.py
    coverage report -m | tee /tmp/coverage
    coverage=$(cat /tmp/coverage | grep -i total | tr -s ' ' | cut -d ' ' -f 4 | cut -d '%' -f 1)
    if (( $coverage < 80 )); then echo 'ERROR: Coverage below accepted threshold!'; exit 1; fi
  after_script:
    - coverage html
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  except:
    - tags
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 hour

pages:
  stage: deploy
  dependencies:
    - unit
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
  only:
    - master
  except:
    - tags
