# The target Python version is 3.7 (minimum version for this module)
target-version = 'py37'

# Maximum allowed length of a line of python code.
line-length = 110

[lint]
# The full list of rules is here: https://docs.astral.sh/ruff/rules/
extend-select = [
    # Additional flake8
    'T',
]
# Ignore the following codes for all files.
# We should work towards decreasing the items in this list.
ignore = [
    'E722',  # Do not use bare `except`
]

[format]
# Use single quotes for non-triple-quoted strings.
quote-style = 'single'